[project]
name = "plane2brain"
version = "0.2.0"
description = "Map 2-photon imaging planes onto the mouse brain atlas"
authors = [
    {name = "International Brain Laboratory", email = "software-devs@internationalbrainlab.org"},
]
dependencies = [
    "iblatlas",
    "matplotlib",
    "numba",
    "numpy",
    "pandas",
    "scipy",
    "seaborn",
    "tqdm",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true

[tool.ruff]
exclude = [
    "src/scripts",
]

[tool.ruff.lint]
ignore = ["E741"]

[dependency-groups]
lint = ["ruff>=0.7.3"]
test = ["pytest"]
